#version: '3'
#services:
#  tests:
#    build:
#      context: .
#      dockerfile: dockerfile
#    env_file:
#      - .env
#    environment:
#      - TEST_DB_HOST=host.docker.internal
#    volumes:
#      - /usr/src/app/node_modules
#      - ./:/usr/src/app

version: '3'

services:
  redis:
    image: redis
    restart: always
    container_name: prac-redis
    ports:
      - 10300:6379